services:
  # PostgreSQL - (cliente)
  postgres:
    image: postgres:17
    container_name: ${POSTGRESQL_NAME}
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
    ports:
      - "${POSTGRESQL_PORT}:5432"
    volumes:
      - ./docker-files/db/postgresql:/docker-entrypoint-initdb.d
    networks:
      - erp-vpc
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRESQL_USER} -d ${POSTGRESQL_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # MongoDB - (Compras)
  mongodb:
    image: mongo:8
    container_name: ${MONGODB_NAME}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DB}
    ports:
      - "${MONGODB_PORT}:27017"
    volumes:
      - ./docker-files/db/mongodb:/docker-entrypoint-initdb.d
    networks:
      - erp-vpc
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')", "-u", "${MONGODB_USER}", "-p", "${MONGODB_PASSWORD}", "--authenticationDatabase", "admin", "--quiet"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  discovery-server:
    build:
      context: .
      dockerfile: ./discovery-server/Dockerfile
    container_name: discovery-server
    ports:
      - "${DISCOVERY_SERVICE_PORT}:8761"
    networks:
      - erp-vpc
    healthcheck:
      test: ["CMD", "curl", "-f", "http://discovery-server:${DISCOVERY_SERVICE_PORT}/actuator/health"]
      interval: 20s
      timeout: 3s
      retries: 5
    restart: on-failure

  config-server:
    build:
      context: .
      dockerfile: ./config-server/Dockerfile
    container_name: config-server
    depends_on:
      discovery-server:
        condition: service_healthy
    ports:
      - "${CONFI_SERVER_PORT}:9000"
    environment:
      - PORT_SERVICE_CONFIG=${CONFI_SERVER_PORT}
      - CONFIG_SERVER_GIT_URI=${CONFI_SERVER_GIT_URI}
      - CONFIG_SERVER_GIT_BRANCH=${CONFI_SERVER_GIT_BRANCH}
      - EUREKA_CLIENT_SERVICE_URL=http://${DISCOVERY_SERVICE_HOST}:${DISCOVERY_SERVICE_PORT}/eureka
    networks:
      - erp-vpc
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://config-server:${CONFI_SERVER_PORT}/actuator/health" ]
      interval: 20s
      timeout: 3s
      retries: 5
    restart: on-failure

  msvc-cliente:
    build:
      context: .
      dockerfile: ./msvc-cliente/Dockerfile
    container_name: msvc-cliente
    depends_on:
      discovery-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
      postgres:
        condition: service_started
    ports:
      - "${MSVC_CLIENTE_PORT}:7010"
    environment:
      - CONFIG_SERVER_CONF_URI=http://${CONFI_SERVER_HOST}:${CONFI_SERVER_PORT}
      - CONFIG_SERVER_PROFILE=${CONFI_SERVER_PROFILE}
      - PORT_SERVICE_CLIENTE=${MSVC_CLIENTE_PORT}
      - EUREKA_CLIENT_SERVICE_URL=http://${DISCOVERY_SERVICE_HOST}:${DISCOVERY_SERVICE_PORT}/eureka
      - BD_POSTGRESQL_URL=jdbc:postgresql://postgres:${MSVC_CLIENTE_BD_PORT}/${MSVC_CLIENTE_BD_NAME}
      - BD_POSTGRESQL_USERNAME=${POSTGRESQL_USER}
      - BD_POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
    networks:
      - erp-vpc

  msvc-compras:
    build:
      context: .
      dockerfile: ./msvc-compras/Dockerfile
    container_name: msvc-compras
    depends_on:
      discovery-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
      mongodb:
        condition: service_started
    ports:
      - "${MSVC_COMPRAS_PORT}:7020"
    environment:
      - CONFIG_SERVER_CONF_URI=http://${CONFI_SERVER_HOST}:${CONFI_SERVER_PORT}
      - CONFIG_SERVER_PROFILE=${CONFI_SERVER_PROFILE}
      - EUREKA_CLIENT_SERVICE_URL=http://${DISCOVERY_SERVICE_HOST}:${DISCOVERY_SERVICE_PORT}/eureka
      - BD_MONGODB_URI=mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@${MONGODB_HOST}:${MONGODB_PORT}/${MONGODB_DB}?authSource=admin
    networks:
      - erp-vpc

  client-oauth2:
    build:
      context: .
      dockerfile: ./client-oauth2/Dockerfile
    container_name: client-oauth2
    depends_on:
      discovery-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
    ports:
      - "${CLOUD_CLIENT_OAUTH2}:9099"
    environment:
      - PORT_CLIENT_OAUTH2=${CLOUD_CLIENT_OAUTH2}
      - CONFIG_SERVER_CONF_URI=http://${CONFI_SERVER_HOST}:${CONFI_SERVER_PORT}
      - CONFIG_SERVER_PROFILE=${CONFI_SERVER_PROFILE}
      - EUREKA_CLIENT_SERVICE_URL=http://${DISCOVERY_SERVICE_HOST}:${DISCOVERY_SERVICE_PORT}/eureka
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
    networks:
      - erp-vpc

  mysql-keycloak:
    image: mysql
    container_name: ${KEY_KC_DB_URL_HOST}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${PORT_MYSQL}:3306"
    networks:
      - erp-vpc
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${MYSQL_USER}", "-p${MYSQL_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  Keycloak:
    image: quay.io/keycloak/keycloak:19.0.1
    container_name: mitocode-keycloak
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: ${KEY_KC_DB}
      KC_DB_URL_HOST: ${KEY_KC_DB_URL_HOST}
      KC_DB_URL_PORT: ${PORT_MYSQL}
      KC_DB_USERNAME: ${MYSQL_USER}
      KC_DB_PASSWORD: ${MYSQL_PASSWORD}
      KC_DB_URL_DATABASE: ${MYSQL_DB}
    ports:
      - "${PORT_KEYCLOAK}:8080"
    depends_on:
      mysql-keycloak:
        condition: service_healthy
    command: ["start-dev"]
    networks:
      - erp-vpc

networks:
  erp-vpc:
    driver: bridge