FROM eclipse-temurin:25-jdk-alpine  AS build

WORKDIR /app

RUN apk add --no-cache maven

COPY . .

RUN mvn clean package -DskipTests -pl msvc-cliente -am

FROM eclipse-temurin:25-jre-alpine
RUN apk add --no-cache curl bash
WORKDIR /app

COPY --from=build /app/msvc-cliente/target/*.jar app.jar

EXPOSE 7010

ENTRYPOINT ["java", "-jar", "app.jar"]